# =============================================================================
# YARN MANAGEMENT SYSTEM - ENVIRONMENT CONFIGURATION
# =============================================================================
# Copy this file to .env and fill in your actual values

# Database Configuration
DB_PASSWORD=your_secure_database_password_here

# JWT Configuration
JWT_SECRET=your_super_secret_jwt_key_here_make_it_long_and_random

# Google Drive API Configuration
# Get these from: https://console.cloud.google.com/
GOOGLE_CLIENT_ID=your_google_client_id
GOOGLE_CLIENT_SECRET=your_google_client_secret
GOOGLE_REDIRECT_URI=http://localhost:3001/api/auth/google/callback

# Ravelry API Configuration
# Get these from: https://www.ravelry.com/pro/developer
RAVELRY_USERNAME=your_ravelry_username
RAVELRY_PASSWORD=your_ravelry_password

# Frontend URLs
FRONTEND_URL=http://localhost:3000
REACT_APP_API_URL=http://localhost:3001/api
REACT_APP_ADMIN_URL=http://localhost:3002

# Production URLs (update these for your domain)
# FRONTEND_URL=https://yarn.yourdomain.com
# REACT_APP_API_URL=https://yarn.yourdomain.com/api
# REACT_APP_ADMIN_URL=https://admin.yourdomain.com

# Backup Configuration (optional)
AWS_ACCESS_KEY_ID=your_aws_access_key
AWS_SECRET_ACCESS_KEY=your_aws_secret_key
S3_BACKUP_BUCKET=yarn-management-backups

# Email Configuration (optional)
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=your_email@gmail.com
SMTP_PASS=your_app_password

# =============================================================================
# GENERATED VALUES (don't edit these manually)
# =============================================================================
# These will be auto-generated by the setup script
DATABASE_URL=postgresql://yarn_user:${DB_PASSWORD}@postgres:5432/yarn_management
REDIS_URL=redis://redis:6379